antora:
  extensions:
  - '@antora/collector-extension'
  - require: '@antora/lunr-extension'
    index_latest_only: true
    index_by_heading: true
  - require: '@springio/antora-extensions/root-component-extension'
    root_component_name: junit
  - require: '@springio/antora-extensions/root-attachments-extension'
  - require: '@springio/antora-xref-extension'
site:
  title: JUnit User Guide
  start_page: junit::overview.adoc
content:
  sources:
  - url: @GIT_REPO_ROOT@
    branches: @GIT_BRANCH_NAME@
    start_path: documentation
    worktrees: true
asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  attributes:
    attribute-missing: warn
    tabs-sync-option: ''
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: css/vendor/tabs.css
      contents: @GIT_REPO_ROOT@/documentation/node_modules/@asciidoctor/tabs/dist/css/tabs.css
    - path: js/vendor/tabs.js
      contents: @GIT_REPO_ROOT@/documentation/node_modules/@asciidoctor/tabs/dist/js/tabs.js
    - path: partials/footer-scripts.hbs
      contents: |
        <script id="site-script" src="{{{uiRootPath}}}/js/site.js" data-ui-root-path="{{{uiRootPath}}}"></script>
        <script async src="{{{uiRootPath}}}/js/vendor/highlight.js"></script>
        <script async src="{{{uiRootPath}}}/js/vendor/tabs.js" data-sync-storage-key="preferred-code-language"></script>
        {{#if env.SITE_SEARCH_PROVIDER}}
        {{> search-scripts}}
        {{/if}}
    - path: partials/head-styles.hbs
      contents: |
        <link rel="stylesheet" href="{{{uiRootPath}}}/css/site.css">
        <link rel="stylesheet" href="{{{uiRootPath}}}/css/vendor/tabs.css">
